run:
  timeout: 60m

linters:
  enable-all: true
  # Disable deprecated linters
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - mnd

    - exhaustruct
    - nlreturn
    - varnamelen
    - lll
    - wsl
    - gosec
    - gomnd
    - gochecknoglobals
    - makezero
    - gci

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400

  exhaustive:
    check:
      - switch
      - map
    # ignore-enum-types: "ResourceName"

  govet:
    enable:
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      # - fieldalignment
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unusedresult

  revive:
    rules:
      - name: atomic
        disabled: false
      - name: blank-imports
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: datarace
        disabled: false
      - name: defer
        disabled: false
      - name: dot-imports
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: exported
        disabled: false
      - name: if-return
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: var-naming
        disabled: false
      - name: var-declaration
        disabled: false
      - name: package-comments
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        disabled: false
      - name: time-naming
        disabled: false
      - name: unexported-return
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: errorf
        disabled: false
      - name: empty-block
        disabled: false
      - name: superfluous-else
        disabled: false
      - name: struct-tag
        disabled: false
        arguments:
          - "json,inline"
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
        disabled: false
      - name: redefines-builtin-id
        disabled: false

  tagalign:
    order:
      - json
      - yaml
      - xml
      - form

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - tailscale.com
          - github.com/google/uuid
          - github.com/loft-sh
          - github.com/go-chi/chi
          - github.com/jba/muxpatterns
          - github.com/klauspost/compress/zstd
          - github.com/metal-stack/go-ipam
          - github.com/invopop/jsonschema

  gomoddirectives:
    replace-allow-list:
      - tailscale.com

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
